version: '3'

services:

  vector:
    image: 'timberio/vector:0.32.1-debian'
    ports: ['9845:9845']
    volumes:
      - './vector.toml:/etc/vector/vector.toml:ro'
    depends_on:
      kafka:
        condition: service_healthy

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    healthcheck:
      test: "/opt/bitnami/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9092"
      interval: 10s
      timeout: 5s
      retries: 5

  arroyo:
    image: ghcr.io/arroyosystems/arroyo:latest
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - '8000:8000'
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: >
      bash -c "/app/arroyo-bin migrate && /app/arroyo-bin cluster"

  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  debezium:
    image: 'bitnami/kafka:latest'
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: >
      bash -c "mkdir -p /tmp/connect-plugins && cd /tmp/connect-plugins
      && curl -OL https://repo1.maven.org/maven2/io/debezium/debezium-connector-jdbc/2.3.2.Final/debezium-connector-jdbc-2.3.2.Final-plugin.tar.gz \
      && tar xvf debezium-connector-jdbc-2.3.2.Final-plugin.tar.gz \
      && curl -OL https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.3.2.Final/debezium-connector-postgres-2.3.2.Final-plugin.tar.gz \
      && tar xvfz debezium-connector-postgres-2.3.2.Final-plugin.tar.gz \
      && /opt/bitnami/kafka/bin/connect-standalone.sh /tmp/connect-standalone.properties /tmp/postgres-sink.properties"
    volumes:
      - ./connect-standalone.properties:/tmp/connect-standalone.properties
      - ./postgres-sink.properties:/tmp/postgres-sink.properties

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
